# Cambia el puerto para evitar conflictos (puedes poner 8081, 8082, etc.)
server.port=8081

spring.application.name=flowerservices

# DATA SOURCE (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5433/flowerservices
spring.datasource.username=postgres
spring.datasource.password=rootpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Apagamos Flyway temporalmente mientras usamos ddl-auto=update
spring.flyway.enabled=false

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect